### ISSUE TITLE
我在运行npm start时遇到了问题

### ISSUE THREAD

**Issue by fg125** [wuhan2020/map-viz#68]
mi@DESKTOP-3GJBFFU MINGW64 ~/Desktop/map-viz (master)
$ npm start

> wuhan2020-map-viz@0.0.1 start C:\Users\mi\Desktop\map-viz
> rm -rf dist/  &&  parcel source/index.html --open

'parcel' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wuhan2020-map-viz@0.0.1 start: `rm -rf dist/  &&  parcel source/index.html --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wuhan2020-map-viz@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mi\AppData\Roaming\npm-cache\_logs\2020-01-31T15_27_22_513Z-debug.log

**Comment by shadowings-zy** [comment]
”This is probably not a problem with npm. There is likely additional logging output above.“由这个log可知是parcel报错了，错误信息如上”'parcel' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒“

🤦‍♂️一团乱码也完全没办法定位错误在哪里啊，不过肯定是parcel的问题了。
个人建议你先删掉node_module文件夹，然后重新npm install一下再看看？

**Comment by tongshuangwu** [comment]
我从slack上看来的解法，疑似跟你是一个问题：
```
在 package.json 的 scripts 里面增加 "win-start": "parcel source/index.html --open"， 然后用 npm run win-start 启动就可以了。
```
另外还有一个解法是，看您是windows电脑，可以考虑装一下WSL，能解决很多不兼容的问题。

**Comment by YaosThinking** [comment]
"D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" install --scripts-prepend-node-path=auto
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! Unexpected end of JSON input while parsing near '...5kYlC0hpyrb7apGfBteP5'

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2020-02-01T13_09_47_650Z-debug.log

**Comment by YaosThinking** [comment]
工程跑不起来
"D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" install --scripts-prepend-node-path=auto
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! Unexpected end of JSON input while parsing near '...5kYlC0hpyrb7apGfBteP5'

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2020-02-01T13_09_47_650Z-debug.log

**Comment by tongshuangwu** [comment]
这是npm在报错，不是我们项目能修的。出现这种问题我觉得只能尝试两步：
1. 升级一下node和npm
2. 转用WSL
